name = "ad-campaign-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8000
ip = "0.0.0.0"

[vars]
JWT_SECRET = "ad-campaign-jwt-secret-2026"
DATABASE_URL = "postgresql://neondb_owner:npg_zA2Hf3LRiTDQ@ep-wild-butterfly-am3ofjd5.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"
